Showing overview block text on movie
sanity-io/example-frontend-next-js pull request #1
Opened 2018-04-16 14:11 UTC by kristofferj

2018-04-16 14:26 UTC, bjoerge commented
Will this display images and other types embedded in the block array?

2018-04-16 14:26 UTC, bjoerge requested changes

2018-04-16 14:26 UTC, bjoerge commented on pages/movie.js
> +    console.log('movie', movie)
This should be removed

2018-04-16 14:29 UTC, bjoerge commented
According to the schema, the block array can contain entries of type `image`, `movie`, `screening` and `person`. It would be good if we could illustrate an example of rendering each of these types.

2018-04-16 16:55 UTC, kristofferj commented
Good point. Then we need to populate the movies data with other block types than normal text

2018-04-17 12:02 UTC, kristofferj commented
On hold. until fixing a GROQ issue.

2018-04-19 10:53 UTC, kristofferj commented
Schema is updated without references. Now has plotSummaries and image

2018-04-19 13:32 UTC, bjoerge approved these changes

2018-04-19 14:25 UTC, merged